eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/tom-yuan/spring-cloud-study/
          searchPaths: config-respo
#          username: your username
#          password: your password
