
server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/tom-yuan/microservice-demo/
#          uri: https://github.com/forezp/SpringcloudConfig/
          searchPaths: respo
#          username: your username
#          password: your password